.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.0 */

.align 2
nonmatching D_8007AA38

dlabel D_8007AA38
    /* 0 8007AA38 */ .asciz "/"
    /* 2F000000 */
.align 2
enddlabel D_8007AA38

nonmatching jtbl_8007AA3C

dlabel jtbl_8007AA3C
    /* 4 8007AA3C 64BC0780 */ .word .L8007BC64
    /* 8 8007AA40 9CBC0780 */ .word .L8007BC9C
    /* C 8007AA44 F4BC0780 */ .word .L8007BCF4
    /* 10 8007AA48 C0BD0780 */ .word .L8007BDC0
    /* 14 8007AA4C D0BD0780 */ .word .L8007BDD0
enddlabel jtbl_8007AA3C
