"""Emit a PROVIDE() linker script pinning every known symbol to its address.

The all-asm baseline references hundreds of symbols by name that are NOT defined
in any object: .bss globals (>= 0x80075800, never in the file image), the
kernel/scratchpad/hardware registers, and BIOS jump-table entries. ld must be told
their fixed addresses or the link fails (and any wrong address would change an
emitted %hi/%lo or %gp_rel byte). We PROVIDE *every* symbol we know (the step-04
corpus + splat's auto-detected undefined lists); PROVIDE is ignored for symbols a
real object already defines, so pinning the superset is safe and guarantees
correct, byte-stable addresses for the rest.

Each ``infile`` holds ``name = 0xADDR;`` lines (// comments and blanks ignored).
"""

from __future__ import annotations

import re
from pathlib import Path

_SYM = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+)")


def run(out: Path, infiles: list[Path]) -> None:
    syms: dict[str, int] = {}  # name -> addr (first definition wins; all should agree)
    for f in infiles:
        for line in Path(f).read_text().splitlines():
            line = line.split("//", 1)[0]
            m = _SYM.match(line)
            if not m:
                continue
            syms.setdefault(m.group(1), int(m.group(2), 16))

    lines = [
        "/* GENERATED by `open-spyro gen-syms-ld` — do not edit.",
        " * PROVIDE() every known symbol at its original address so the",
        " * all-asm baseline links byte-identically. */",
    ]
    for name in sorted(syms, key=lambda n: syms[n]):
        lines.append(f"PROVIDE({name} = 0x{syms[name]:08X});")
    Path(out).write_text("\n".join(lines) + "\n")
    print(f"gen_syms_ld: wrote {len(syms)} PROVIDE() lines to {out}")
