"""Fixed-VMA text slot fragment for the main EXE.

Emits config/spyro.main.slots.ld: one anchored slot per function, in VMA order,

    . = 0x80012204 ;
    build/main/asm/text.o(.text.main)

and, for any function that now has a C match in src/c/<name>.c, the compiled
object fills the same slot instead of (well, alongside the HAVE_C-emptied) asm:

    . = 0x8005956c ;
    build/main/asm/text.o(.text.ComputeSaveGameChecksum)   # emptied by --defsym
    build/main/c/ComputeSaveGameChecksum.o(.text)

The ``. = 0xVMA`` anchors pin every function at its original address, so a C
override that fits its slot reproduces the original bytes and everything after it
stays byte-identical. If an override OVERFLOWS its slot, the next anchor would move
the location counter backwards and ``ld`` fails loudly — the slot-fit guard. The
fragment is INCLUDEd by config/spyro.main.ld in place of the old monolithic
``text.o(.text)``.

Inputs: config/text_layout.json (full ordered inventory from sectionize) and the
set of src/c/*.c overrides present.
"""

from __future__ import annotations

import json

from open_spyro.paths import repo_root

# The slots are INCLUDEd inside the `.main 0x80010000 :` output section, where the
# location counter `.` is SECTION-RELATIVE (an absolute `. = 0x800122xx` wraps to
# base + offset). So anchors are written as VMA - base. main always loads here.
MAIN_BASE = 0x80010000


def run() -> None:
    repo = repo_root()
    layout = repo / "config/text_layout.json"
    src_c = repo / "src/c"
    out = repo / "config/spyro.main.slots.ld"

    have_c = {p.stem for p in src_c.glob("*.c")} if src_c.is_dir() else set()

    funcs = [f for f in json.loads(layout.read_text())["functions"] if f["vram"] is not None]
    funcs.sort(key=lambda f: f["vram"])

    lines = [
        "/* Auto-generated by `open-spyro gen-slots-ld` — do not edit. */",
        "/* Fixed-VMA text slots; INCLUDEd by config/spyro.main.ld. */",
    ]
    used: list[str] = []
    for f in funcs:
        name, vram = f["name"], f["vram"]
        lines.append(f"    . = 0x{vram - MAIN_BASE:08x} ;")
        lines.append(f"    build/main/asm/text.o(.text.{name})")
        if name in have_c:
            lines.append(f"    build/main/c/{name}.o(.text)")
            used.append(name)
    out.write_text("\n".join(lines) + "\n")
    print(f"gen_slots_ld: {len(funcs)} slots, {len(used)} C override(s) -> {out.relative_to(repo)}")
    if used:
        print("  overrides: " + ", ".join(sorted(used)))
