"""Emit a splat config per overlay from config/overlays.json.

Run by ``make split`` before splitting; consumes ONLY the committed overlay table
(config/overlays.json).

Each overlay is one ``code`` segment loaded at the shared overlay VRAM. Its file is
laid out [LONG id][.rodata][.text][.data][.bss]; we dump the leading id+rodata as
``rodata`` and the trailing data as ``data``, and disassemble the middle as ``asm``
(text). The leading blob is ``rodata`` (not ``data``) on purpose: that puts it
first in splat's own generated <name>.ld so the link reproduces the file's byte
order, and the build uses that auto-updating ld directly. With zero seeded symbols
every function comes out as an unnamed func_xxxxxxxx — naming grows as overlays are
decompiled.
"""

from __future__ import annotations

import json

from open_spyro.paths import repo_root

TEMPLATE = """\
# AUTO-GENERATED by `open-spyro gen-overlay-yaml` from config/overlays.json — do not edit.
# Overlay '{name}' (psyq overlay id {overlay_id}), extracted from WAD.WAD.
name: {name}
sha1: {sha1}
options:
  basename: {name}
  target_path: disc/orig/overlays/{ovl_file}
  elf_path: build/overlays/{name}.elf
  base_path: ../..   # repo root (this yaml lives in config/overlays/)
  platform: psx
  compiler: PSYQ
  asm_path: asm/overlays/{name}
  src_path: src/overlays/{name}
  build_path: build/overlays/{name}
  # splat's generated linker script + auto symbol lists are *committed* under
  # config/overlays/ (NOT build/, which is gitignored). They are derived metadata —
  # ld directives + symbol/address lists, the same legal category as asm/ — and
  # committing them lets CI relink every overlay from committed asm WITHOUT the
  # original disc (the disc is never present in CI). The dev regenerates them with
  # `make split` (which needs the disc) and commits them alongside asm changes.
  ld_script_path: config/overlays/{name}.ld
  undefined_syms_auto_path: config/overlays/{name}.undefined_syms.auto.txt
  undefined_funcs_auto_path: config/overlays/{name}.undefined_funcs.auto.txt
  find_file_boundaries: False
  o_as_suffix: True
  use_legacy_include_asm: False
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False
  section_order: [".rodata", ".text", ".data", ".bss"]
  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: {name}
    type: code
    start: 0x0
    vram: {vram:#x}
    subsegments:
      # Leading [LONG id + const blob] is labeled `rodata` (not `data`) so splat's
      # own generated <name>.ld lands it FIRST (.rodata group), matching the file
      # layout [id+.rodata][.text][.data] — same convention as config/spyro.main.yaml's
      # rodata_pre. This lets the build use splat's auto-updating ld directly, so it
      # keeps working as functions are split out to C.
      - [0x0, rodata, rodata]
      - [{text_off:#x}, asm, text]
      - [{data_off:#x}, data, data]
  - [{size:#x}]
"""


def run() -> None:
    repo = repo_root()
    overlays_json = repo / "config/overlays.json"
    out_dir = repo / "config/overlays"

    data = json.loads(overlays_json.read_text())
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for r in data["overlays"]:
        path = out_dir / f"{r['name']}.yaml"
        path.write_text(TEMPLATE.format(**r))
        written.append(path.name)
    print(f"gen_overlay_yaml: wrote {len(written)} configs -> {out_dir.relative_to(repo)}/")
