"""The CI PR "progress delta" comment body.

Formerly an inline ``python3`` heredoc in ``.github/workflows/ci.yml``; lifted
here so it is committed, lintable, and testable. Exposed through the umbrella CLI
as ``open-spyro progress-delta``:

    open-spyro progress-delta \\
        --base-ref main --head-json progress.json --base-md /tmp/base_progress.md

Head numbers come from the freshly generated ``progress.json`` (precise). Base
numbers are parsed from the base branch's tracked ``PROGRESS.md`` headline — we
read it from PROGRESS.md (not progress.json) because progress.json is a gitignored
build artifact and so is NOT committed on the base branch. A missing/empty base
file yields zeros (delta measured from 0).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

# Matches the PROGRESS.md headline, e.g.
#   **Game code matched: 540 / 2,255,456 bytes (0.02%)** — generated by ...
HEADLINE = re.compile(r"Game code matched:\s*([\d,]+)\s*/\s*([\d,]+)\s*bytes\s*\(([\d.]+)%\)")


def parse_base_md(text: str) -> tuple[float, int]:
    """(matched_pct, matched_bytes) from a PROGRESS.md headline; (0, 0) if absent."""
    m = HEADLINE.search(text)
    if not m:
        return 0.0, 0
    matched_bytes = int(m.group(1).replace(",", ""))
    pct = float(m.group(3))
    return pct, matched_bytes


def render(head: dict, base_pct: float, base_bytes: int, base_ref: str) -> str:
    hp = float(head.get("matched_pct", 0.0))
    hb = int(head.get("matched_bytes", 0))
    tot = int(head.get("total_code_bytes", 0))
    fn = int(head.get("total_functions", 0))
    dpct = hp - base_pct
    dby = hb - base_bytes
    arrow = "▲" if dby > 0 else ("▼" if dby < 0 else "—")
    return (
        f"**Match progress:** {hp:.2f}% ({hb:,} / {tot:,} bytes, {fn:,} game functions)  \n"
        f"Δ vs `{base_ref}`: {arrow} {dpct:+.2f}% ({dby:+,} bytes)"
    )


def run(base_ref: str, head_json: Path, base_md: Path) -> None:
    """Print the PR comment body comparing ``head_json`` to ``base_md``'s headline."""
    head = json.loads(head_json.read_text())
    base_text = base_md.read_text() if base_md.exists() else ""
    base_pct, base_bytes = parse_base_md(base_text)
    print(render(head, base_pct, base_bytes, base_ref))
