.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.0 */

nonmatching D_80084A18

dlabel D_80084A18
    /* 9FE0 80084A18 00000000 */ .word 0x00000000
    /* 9FE4 80084A1C 00000000 */ .word 0x00000000
    /* 9FE8 80084A20 00000000 */ .word 0x00000000
    /* 9FEC 80084A24 00000000 */ .word 0x00000000
    /* 9FF0 80084A28 00000000 */ .word 0x00000000
    /* 9FF4 80084A2C 00000000 */ .word 0x00000000
    /* 9FF8 80084A30 00000000 */ .word 0x00000000
    /* 9FFC 80084A34 00000000 */ .word 0x00000000
enddlabel D_80084A18
