.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.0 */

nonmatching D_80087218

dlabel D_80087218
    /* C7E0 80087218 00000000 */ .word 0x00000000
    /* C7E4 8008721C 00000000 */ .word 0x00000000
    /* C7E8 80087220 00000000 */ .word 0x00000000
    /* C7EC 80087224 00000000 */ .word 0x00000000
    /* C7F0 80087228 00000000 */ .word 0x00000000
    /* C7F4 8008722C 00000000 */ .word 0x00000000
    /* C7F8 80087230 00000000 */ .word 0x00000000
    /* C7FC 80087234 00000000 */ .word 0x00000000
enddlabel D_80087218
